name: webkeys
description: clean arch, testing.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dio: ^5.3.0
  get_it: ^7.6.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  permission_handler: ^11.0.0
  geolocator: ^10.0.1
  geocoding: ^2.1.0
  path_provider: ^2.0.15
  intl: ^0.18.1
  lottie: ^2.6.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/


